#ifndef PIN_MAPPING
#define PIN_MAPPING

typedef unsigned char PinType;
typedef PinType ArrSizeType;
#include "MappingMacro.h"

#ifdef EVENT_OS
START_PIN_ARRAY
#if defined(ESP8266) 
// ADD REAL HARDWARE PIN TO ARRAY. ALL PINS ADDED TO ARRAY WILL SUPPORT EVENTS
ADD_PIN(5)
ADD_PIN(4)
ADD_PIN(14)
ADD_PIN(12)
ADD_PIN(13)
#elif defined(ESP32)
ADD_PIN(4)
ADD_PIN(5)
ADD_PIN(13)
ADD_PIN(14)
ADD_PIN(15)
ADD_PIN(16)
ADD_PIN(17)
ADD_PIN(18)
ADD_PIN(19)
ADD_PIN(21)
ADD_PIN(22)
ADD_PIN(23)
ADD_PIN(25)
ADD_PIN(26)
ADD_PIN(27)
ADD_PIN(32)
ADD_PIN(33)
ADD_PIN(34)
ADD_PIN(35)
ADD_PIN(36)
ADD_PIN(39)
#elif  defined(ARDUINO_AVR_UNO) || defined(ARDUINO_AVR_NANO)
ADD_PIN(2)
ADD_PIN(3)
ADD_PIN(4)
ADD_PIN(5)
ADD_PIN(6)
ADD_PIN(7)
ADD_PIN(8)
ADD_PIN(9)
ADD_PIN(10)
ADD_PIN(11)
ADD_PIN(12)
ADD_PIN(13)
#else
ADD_PIN(2)
ADD_PIN(3)
ADD_PIN(4)
ADD_PIN(5)
ADD_PIN(6)
ADD_PIN(7)
ADD_PIN(8)
ADD_PIN(9)
ADD_PIN(10)
ADD_PIN(11)
ADD_PIN(12)
ADD_PIN(13)
#endif
END_PIN_ARRAY

#endif // EVENT_OS

#endif // PIN_MAPPING